[package]
name = "timely_experiment"
version = "0.1.0"
authors = ["Murray Dunne <mrmurraydunne@gmail.com> Calum Bruton <calumbruton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timely = { path = "../timely/timely" }
<<<<<<< HEAD
pyo3 = "0.8.2"
=======
opencv = {version = "0.26.6", default-features = false, features = ["opencv-41"]}
>>>>>>> Frame retrieval operator
